apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: besamly2018/rpc-server
          command: ["npm", "run", "start"]
          resources:
            requests:
              cpu: "500m"
              memory: "50Mi"
            limits:
              cpu: "500m"
              memory: "300Mi"
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RPC_HOST
              value: "0.0.0.0:50051"
            - name: NATS_URL
              value: 'http://nats-srv:4222'
          
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 50051
      targetPort: 50051
