apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: autosacle-client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-depl
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    # scaleDown:
    #   stabilizationWindowSeconds: 30
    #   policies:
    #   - type: Percent
    #     value: 100
    #     periodSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max

