# apiVersion: autoscaling/v2beta2
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: autosacle-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-depl
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
  # !!! GKE does not recognize the field of behavior
  # behavior:
  #   scaleDown:
  #     stabilizationWindowSeconds: 30
  #     policies:
  #       - type: Percent
  #         value: 100
  #         periodSeconds: 5
  #   scaleUp:
  #     stabilizationWindowSeconds: 0
  #     policies:
  #       - type: Percent
  #         value: 100
  #         periodSeconds: 5
  #       - type: Pods
  #         value: 4
  #         periodSeconds: 15
  #     selectPolicy: Max
