name: Update on client service

on:
  push:
    branches:
      - master
    paths:
      - "client/**"

env:
  GKE_PROJECT: ibct-microservices
  GKE_CLUSTER_NAME: ibct-microservices-cluster-1
  GKE_REGION: asia-northeast1-a
  # GKE_EMAIL: ${{secrets.GKE_EMAIL}}
  # GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_IMAGE_NAME: besamly2018/rpc-client
  DEPLOYMENT_TO_ROLLOUT: client-depl

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: cd client && docker build -t $DOCKER_IMAGE_NAME .

      - name: Docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Docker image push
        run: docker push $DOCKER_IMAGE_NAME

      # !!! DEPRECATED VERSION 
      # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #   with:
      #     version: "270.0.0"
      #     service_account_email: ${{secrets.GKE_EMAIL}}
      #     service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # !!! NEW VERSION
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ibct-microservices
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          export_default_credentials: true

      - name: Get GKE cluster context
        run: |-
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_REGION --project $GKE_PROJECT

      - name: Test if context is succesfully loaded
        run: |-
          kubectl get pods

      - name: Rollout client deployment
        run: |-
          kubectl rollout restart deployment $DEPLOYMENT_TO_ROLLOUT
